const globals = {
  window: "readonly",
  document: "readonly",
  console: "readonly",
  requestAnimationFrame: "readonly",
  cancelAnimationFrame: "readonly",
  setTimeout: "readonly",
  clearTimeout: "readonly",
  setInterval: "readonly",
  clearInterval: "readonly",
  performance: "readonly",
  location: "readonly",
  navigator: "readonly",
  URLSearchParams: "readonly",
  localStorage: "readonly",
  sessionStorage: "readonly",
  Image: "readonly",
  Audio: "readonly",
  Math: "readonly",
  JSON: "readonly",
  Object: "readonly",
  Array: "readonly",
  Number: "readonly",
  String: "readonly",
  Boolean: "readonly",
  Date: "readonly",
  Map: "readonly",
  Set: "readonly",
  Promise: "readonly",
  Error: "readonly",
  isNaN: "readonly",
  isFinite: "readonly",
  parseInt: "readonly",
  parseFloat: "readonly",
  HTMLElement: "readonly",
  HTMLCanvasElement: "readonly",
  CanvasRenderingContext2D: "readonly",
  AudioContext: "readonly",
  webkitAudioContext: "readonly",
  KeyboardEvent: "readonly",
  MouseEvent: "readonly",
  Event: "readonly",
  alert: "readonly",
  confirm: "readonly",
  prompt: "readonly",
};

module.exports = [
  {
    files: ["**/*.js", "tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals,
    },
    rules: {
      "no-undef": "error",
      "no-unused-vars": ["warn", { args: "none", varsIgnorePattern: "^_" }],
      "no-unreachable": "error",
      "no-dupe-keys": "error",
      "no-dupe-args": "error",
      "no-redeclare": "error",
      "no-const-assign": "error",
      "no-func-assign": "error",
      "use-isnan": "error",
      "valid-typeof": "error",
    },
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      globals: {
        ...globals,
        process: "readonly",
        __dirname: "readonly",
        require: "readonly",
        module: "readonly",
      },
    },
  },
];
